/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuarios;

import Clases.Enterprise;
import Clases.Factura;
import static Interfaces.Reportes.orden;
import TDA.NodoLS;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author CARLOS
 */
public class Aviso extends javax.swing.JFrame {

    public Factura f = new Factura();
    public String tarjeta;
    public String propietario;

    /**
     * Creates new form Aviso
     */
    public Aviso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENSAJE DE CONFIRMACION");

        jLabel2.setText("¿Esta seguro de realizar la siguiente compra?");

        jButton1.setText("No");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Si");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nombre.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(jButton1)
                            .addGap(102, 102, 102)
                            .addComponent(jButton2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(nombre)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Carrito c = new Carrito();
        c.setResizable(false);
        c.dueno.setText(propietario);
        c.tarjeta.setText(tarjeta);
        c.setLocationRelativeTo(null);
        c.nombre.setText(nombre.getText());
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Carrito c = new Carrito();

        System.out.println("");
        Enterprise.facturas.añadirR(f);
        Enterprise.facturas.imprimir();
        JOptionPane.showMessageDialog(null, "Compra realizada con exito, ingrese la direccion donde desea guardar su factura");
        Enterprise.simpleList.buscarTodo2(nombre.getText()).carrito.primero = null;
         Enterprise.simpleList.buscarTodo2(nombre.getText()).carrito.tamaño = 0;
        Enterprise.simpleList.buscarTodo2(nombre.getText()).carrito.imprimir();
        Enterprise.simpleList.buscarTodo2(nombre.getText()).toString();

        String direccion = SeleccionarArchivo("pdf");
        GenerarFactura(direccion);

        I i = new I();
        i.setBounds(0, 0, 800, 700);
        i.nombre.setText(nombre.getText());
        i.setResizable(false);
        i.setLocationRelativeTo(null);
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aviso().setVisible(true);
            }
        });
    }

    public void GenerarFactura(String ruta) {
        String name = Enterprise.facturas.buscar(propietario).getNombre();
        String nit = Integer.toString(Enterprise.facturas.buscar(propietario).getNit());
        String dire = Enterprise.facturas.buscar(propietario).getDireccion();
        String tar = Integer.toString(Enterprise.facturas.buscar(propietario).getTarjeta());
        String id = Integer.toString(Enterprise.facturas.buscar(propietario).getNumero());
        String fech = Enterprise.facturas.buscar(propietario).getFecha();
        String hora = Enterprise.facturas.buscar(propietario).getHora();
        String sub = String.valueOf(Enterprise.facturas.buscar(propietario).getTotal());
        try {
            FileOutputStream archivo = new FileOutputStream(ruta);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();;
            doc.add(new Paragraph("                                        Factura AMAUSAC \n \n"
                    + "Factura No. :       [" + id + "] \n"
                    + "A nombre de:        [" + name + "] \n"
                    + "No. de Nit:        [" + nit + "] \n"
                    + "No. de Tarjet:   [" + tar + "] \n"
                    + "Tipo de Cliente: [" + "Normal]" + "\n"
                    + "Tipo de Compra:  [" + "Compra Normal]" + "\n"
                    + "A Direccion:       [" + dire + "] \n"
                    + "Fecha:             [" + fech + "] \n"
                    + "Hora:               [" + hora + "] \n"
                    + "Descuento:          [0.00] \n"
                    + "Subtotal:           [" + sub + "] \n"
                    + "Total:              [ " + sub + "] \n"));
            doc.close();
        } catch (Exception e) {

        }
        Desktop abrir;
        File file = new File(ruta);
        if (Desktop.isDesktopSupported()) {
            abrir = Desktop.getDesktop();
            try {
                abrir.open(file);
            } catch (IOException exx) {
                exx.getStackTrace();
            }
        } else {
            System.out.println("No");
        }

    }

    public String SeleccionarArchivo(String restriccion) {
        try {
            JFileChooser JfC = new JFileChooser();
            JfC.setAcceptAllFileFilterUsed(false);
            JfC.setFileFilter(new FileNameExtensionFilter("Archivos con extension *." + restriccion, restriccion));
            JfC.setCurrentDirectory(new File("Escritorio"));
            JfC.showOpenDialog(null);
            String ruta = JfC.getSelectedFile().getAbsolutePath();
            return ruta;
        } catch (Exception E) {
            System.err.println("Error al abrir el archivo");
            return "";
        }
    }
    
    public void elim(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
