/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Enterprise;
import Clases.Usuario;
import TDA.ListaSimple;
import TDA.NodoLCS;
import TDA.NodoLS;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author CARLOS
 */
public class Reportes extends javax.swing.JFrame {

    public static String destino = "C:\\Users\\CARLOS\\Documents\\universidad\\cancelan.pdf";
    public static String destino2 = "C:\\Users\\CARLOS\\Documents\\universidad\\cincoCancelan.pdf";

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Productos que tuvieron Oferta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Productos Comprado por cada usuario");

        jButton3.setText("10 Producto más vendidos");

        jButton4.setText("Usuarios que han cancelado compras ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5 Usuario que más cancelan compras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("5 facturas con más productos");

        jButton7.setText("Regresar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addGap(30, 30, 30)
                .addComponent(jButton7)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!Enterprise.usuariosCancelan.estaVacia()) {
            UsuariosCancelan(destino);
        } else {
            JOptionPane.showMessageDialog(null, "No se han realizado cancelaciones");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            html();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Admin a = new Admin();
        a.setLocationRelativeTo(null);
        a.setResizable(false);
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CincoUsuariosCancelan(destino2);
        Cinco s = new Cinco();
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    public void html() throws IOException {
        Enterprise.productoOferta.imprimir();
        javax.swing.JFileChooser jf1 = new javax.swing.JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo HTML", "html");
        jf1.setFileFilter(filtro);
        String ruta = "";

        try {
            if (jf1.showSaveDialog(null) == jf1.APPROVE_OPTION) {
                ruta = jf1.getSelectedFile().getAbsolutePath() + ".html";
                FileOutputStream listado;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            FileWriter archivo = new FileWriter(ruta);
            PrintWriter escritura = new PrintWriter(archivo);
            escritura.println("<html>");
            escritura.println("<head>" + "<title>PruebaHTML1</title></head>");
            escritura.println("<body>");
            escritura.println("<h1>Productos que tuvieron oferta</h1>");
            escritura.println("<br>");
            escritura.println("<table border = 3>");
            escritura.println("<tr>");
            escritura.println("<td><center><b>Nombre          </b></center></td>");
            escritura.println("<td><center><b>Descripcion           </b></center></td>");
            escritura.println("<td><center><b>Precio       </b></center></td>");
            escritura.println("</tr>");
            NodoLCS aux = Enterprise.productoOferta.inicio;
            for (int i = 0; i < Enterprise.productoOferta.contador; i++) {
                escritura.println("<tr>");
                escritura.println("<td><center>" + aux.producto.getNombre() + "</center></td>");
                escritura.println("<td><center>" + aux.producto.getDescripcion() + "</center></td>");
                escritura.println("<td><center>" + String.valueOf(aux.producto.getPrecio()) + "</center></td>");
                escritura.println("</tr>");
                aux = aux.siguiente;
            }
            escritura.println("</table>");
            escritura.println("</body>");
            escritura.println("</html>");
            archivo.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        Desktop abrir;
        File file = new File(ruta);
        if (Desktop.isDesktopSupported()) {
            abrir = Desktop.getDesktop();
            try {
                abrir.open(file);

            } catch (IOException exx) {
                exx.getStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo abrir el archivo");
        }

    }

    public void UsuariosCancelan(String ruta) {
        // NodoLS aux = Enterprise.usuariosCancelan.getInicio();
        try {
            FileOutputStream archivo = new FileOutputStream(ruta);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            PdfPTable table = new PdfPTable(3);
            table.completeRow();
            table.addCell("Nombre");
            table.addCell("E-Mail");
            table.addCell("No. de cancelaciones");
            table.completeRow();

            for (NodoLS aux = Enterprise.usuariosCancelan.getInicio(); aux != null; aux = aux.getSiguiente()) {
                table.addCell(aux.getUser().getName());
                table.addCell(aux.getUser().getEmail());
                table.addCell(Integer.toString(aux.getUser().cancelaciones));
                table.completeRow();
            }

            doc.add(new Paragraph("          Lista de usuarios que han cancelado compras \n \n"));
            doc.add(table);
            doc.close();
        } catch (Exception e) {

        }
        Desktop abrir;
        File file = new File(ruta);
        if (Desktop.isDesktopSupported()) {
            abrir = Desktop.getDesktop();
            try {
                abrir.open(file);
            } catch (IOException exx) {
                exx.getStackTrace();
            }
        } else {
            System.out.println("No");
        }

    }

    public static void orden(ListaSimple ordenar) {
        if (!ordenar.estaVacia()) {
            NodoLS aux = ordenar.getInicio();
            NodoLS actual;
            Usuario temporal;
            while (aux.getSiguiente() != null) {
                actual = aux.getSiguiente();
                while (actual != null) {
                    if (aux.getUser().cancelaciones < actual.getUser().cancelaciones) {
                        temporal = aux.getUser();
                        aux.setUser(actual.getUser());
                        actual.setUser(temporal);
                    }
                    actual = actual.getSiguiente();
                }
                aux = aux.getSiguiente();
            }
        } else {
            System.out.println("Lista vacia");
        }
        ordenar.imprimir();
    }

    public void CincoUsuariosCancelan(String ruta) {
        orden(Enterprise.usuariosCancelan);
        try {
            FileOutputStream archivo = new FileOutputStream(ruta);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            PdfPTable table = new PdfPTable(3);
            table.completeRow();
            table.addCell("Nombre");
            table.addCell("E-Mail");
            table.addCell("No. de cancelaciones");
            table.completeRow();

            if (Enterprise.usuariosCancelan.getContador() < 5) {
                for (NodoLS aux = Enterprise.usuariosCancelan.getInicio(); aux != null; aux = aux.getSiguiente()) {
                    table.addCell(aux.getUser().getName());
                    table.addCell(aux.getUser().getEmail());
                    table.addCell(Integer.toString(aux.getUser().cancelaciones));
                    table.completeRow();
                }
            } else {
                NodoLS aux2 = Enterprise.usuariosCancelan.getInicio();
                for (int i = 0; i < 5; i++) {
                    table.addCell(aux2.getUser().getName());
                    table.addCell(aux2.getUser().getEmail());
                    table.addCell(Integer.toString(aux2.getUser().cancelaciones));
                    table.completeRow();
                    aux2 = aux2.getSiguiente();
                }
            }

            doc.add(new Paragraph("          Lista de usuarios que han cancelado compras \n \n"));
            doc.add(table);
            doc.close();
        } catch (Exception e) {

        }
        Desktop abrir;
        File file = new File(ruta);
        if (Desktop.isDesktopSupported()) {
            abrir = Desktop.getDesktop();
            try {
                abrir.open(file);
            } catch (IOException exx) {
                exx.getStackTrace();
            }
        } else {
            System.out.println("No");
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
